export const FETCH_COMPANY_ERROR ="FETCH_COMPANY_ERROR";
export const FETCH_COMPANY_SUCCESS ="FETCH_COMPANY_SUCCESS";
export const FETCH_COMPANY_INPROGRESS ="FETCH_COMPANY_INPROGRESS";


export const FETCH_EMPLOYEE_ERROR ="FETCH_EMPLOYEE_ERROR";
export const FETCH_EMPLOYEE_SUCCESS ="FETCH_EMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEE_INPROGRESS ="FETCH_EMPLOYEE_INPROGRESS";


export const DELETE_COMPANY_ERROR ="DELETE_COMPANY_ERROR";
export const DELETE_COMPANY_SUCCESS ="DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_INPROGRESS ="DELETE_COMPANY_INPROGRESS";